name: CristichiCasinosDeCartel
main: main.CristichiCasinosCartel
version: 1.15
api-version: 1.13
depend: [Vault, Essentials]
commands:
  criscasinocartel:
    description: Controla el plugin.
    aliases: [cc, ccc, cdc]
    usage: /cc help

permissions:
  casinosdecartel.*:
    description: Permite acceso a todo.
    children:
      casinosdecartel.admin: true
      casinosdecartel.crear: true
      casinosdecartel.usar: true
  casinosdecartel.admin:
    description: Permite utilizar comandos administrativos.
    default: op
    children:
      casinosdecartel.crear: true
      casinosdecartel.usar: true
  casinosdecartel.crear:
    description: Permite crear casinos de cartel. El precio puede ser cualquiera deseado.
    default: false
  casinosdecartel.usar:
    description: Permite usar casinos de cartel al precio que esté especificado.
    default: true