name: CristichiCasinosDeCartel
main: main.CristichiCasinosCartel
version: 0.115
api-version: 1.13
depend: [Vault, Essentials]
commands:
  criscasinocartel:
    description: Controla el plugin.
    aliases: [cc, ccc]
    usage: /cc help