name: CristichiCasinosDeCartel
main: main.CristichiCasinosCartel
version: 0.115
api-version: 1.13
depend: [Vault]
commands:
  casinocartel:
    description: Controla el plugin.
    aliases: [ccc]
    usage: /ccc help